functions exercises
andreykan8/php_learn pull request #3
Opened 2021-07-27 18:41 UTC by andreykan8

2021-07-27 18:57 UTC, nizamitomilovs requested changes

2021-07-27 18:57 UTC, nizamitomilovs commented on php_basics/functions.php
> +function codelex($str) : string {
забыл подать тип в переменную функции, правильный синтакс функции 
function codelex(string $str): string 
{
}

2021-07-27 18:57 UTC, nizamitomilovs commented on php_basics/functions.php
> +    return "$str" . " Codelex";
на забывай приорите signle quotes -> double quotes, когда складываешь переменную не нужно вкладывать его в стринг, php поймет и без $str . ' Codelex';

2021-07-27 18:57 UTC, nizamitomilovs commented on php_basics/functions.php
> +echo codelex("Hello");
single quote -> doublequote only if neccesery

2021-07-27 18:57 UTC, nizamitomilovs commented on php_basics/functions.php
> +            echo "$key has not reached 18 years old\n";
будет правильней как ты делал сначала функция должа делать действие или возвращать его, она не должна выводить результат пользователю: return $key . ' has not reached 18 years old' . PHP_EOL;

2021-07-27 18:57 UTC, nizamitomilovs commented on php_basics/functions.php
> +function age_loop(array $arr) {
перечитай PSR1 and PSR2, название функция всегда имеет дизайн camelCase, используй названия переменных по которым будет понятно что ты подаешь в них, function ageLoop(array $persons)

2021-07-27 18:57 UTC, nizamitomilovs commented on php_basics/functions.php
> +$my_array = [3, 8, 6, 3.2, 'hello'];
variables only camelCase

2021-07-27 19:01 UTC, nizamitomilovs commented
переменная внутри стринга использует только при необходимости и ставить точку не обзательно
"$name is $age years old";
приорите всегда на single quote по той же причине работает быстрее, переход на стиль выше только когда у тебя больше нету выбора, такиие случаи бывают при работе с html, правильный синтакс:
$name . ' is ' . $age . ' years old';

2021-07-28 18:20 UTC, andreykan8 commented on php_basics/functions.php
> +            echo "$key has not reached 18 years old\n";
Согласен, но если использовать return, то цикл прерывается, а в задании сказано напечатать все объекты в массиве. Получается надо использовать функцию внутри цикла, а не наоборот как сейчас?

2021-07-28 19:15 UTC, nizamitomilovs approved these changes

2021-07-28 19:17 UTC, merged